### ISSUE TITLE
怎么配置

### ISSUE THREAD

**Issue by starkong2022** [idranme/koishi-plugin-music-voice#3]
安装了，启动时提示配置不正确
![Screenshot_20240516_195326.jpg](https://github.com/idranme/koishi-plugin-music-downloadvoice-api/assets/115393420/36955c30-9481-4efb-8a82-a068d8483517)

**Comment by idranme** [comment]
你看看哪些配置项没有选。

**Comment by starkong2022** [comment]
你这个必须要选图片模式的吗，开了才可以使用

**Comment by idranme** [comment]
> 你这个必须要选图片模式的吗，开了才可以使用

看你自己的需求。
