### ISSUE TITLE
前台显示发生未知错误

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [idranme/koishi-plugin-music-voice#5]
![微信图片_20240708072729](https://github.com/idranme/koishi-plugin-music-downloadvoice-api/assets/141598320/c45e88b8-b6b5-463b-9eb3-21dc114deb3a)

**Comment by idranme** [comment]
puppeteer 插件的版本是多少？

**Comment by HX-Wrdzgzs** [comment]
3.8.4

**Comment by idranme** [comment]
浏览器版本是多少？

**Comment by HMSXEF** [comment]
这跟我浏览器有什么关联呢？

**Comment by HX-Wrdzgzs** [comment]
这跟浏览器有什么关联呢？
前台显示指：qq群触发music点歌插件时显示**发生未知错误**

**Comment by idranme** [comment]
> 这跟浏览器有什么关联呢？
> 前台显示指：qq群触发music点歌插件时显示**发生未知错误**

那个是 **puppeteer 报的错误**，puppeteer 使用了浏览器。

**Comment by HX-Wrdzgzs** [comment]
Emm，但是我使用的是模板安装

**Comment by idranme** [comment]
请前往 [puppeteer](https://github.com/puppeteer/puppeteer) 仓库寻求帮助。
