### ISSUE TITLE
linux 上中文会有乱码，疑似无字体

### ISSUE THREAD

**Issue by CaiJingLong** [idranme/koishi-plugin-music-voice#6]
<img width="239" alt="image" src="https://github.com/idranme/koishi-plugin-music-downloadvoice-api/assets/14145407/b41c28b4-0965-4bc1-925f-a989a146c0d9">

使用的是 NapCatQQ+Koishi 的方案

系统是 debian11，无GUI的版本，也就是服务器环境
我在某 debian12，带桌面的版本上无乱码

```sh
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

字体应该在哪里配置，或者我应该下载哪个字体？

**Comment by idranme** [comment]
https://www.bing.com/
`font-family: PingFang SC, Hiragino Sans GB, Microsoft YaHei, SimSun, sans-serif;`

**Comment by CaiJingLong** [comment]
我在你推送新版本前的解决方案是安装一个字体 `sudo apt-get install fonts-wqy-zenhei`，并重启 koishi
