### ISSUE TITLE
生成语音时报错

### ISSUE THREAD

**Issue by kongxiangyiren** [idranme/koishi-plugin-music-voice#7]
![image](https://github.com/user-attachments/assets/d65738fb-fb9d-4b26-934d-f8ad3cd0139f)

**Comment by idranme** [comment]
更新 music-downloadvoice-api 到最新版本

**Comment by kongxiangyiren** [comment]
![image](https://github.com/user-attachments/assets/9a8e5b3f-a6da-4cc4-a303-3e3681e03ce7)
![image](https://github.com/user-attachments/assets/6edbc6ad-c7e7-45ed-b4f2-837057065566)
都是最新的插件

**Comment by idranme** [comment]
你用了哪个地区的网络？

**Comment by kongxiangyiren** [comment]
知道了，我服务器在国外，qq音乐把国外禁用了，只能听网易云
