### ISSUE TITLE
前台显示生成语音中，后台开始报错

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [idranme/koishi-plugin-music-voice#9]
![Screenshot_20240728_230541_com.huawei.browser.jpg](https://github.com/user-attachments/assets/2bdcc5f4-8573-4655-8d7b-137c558b8794)

![Screenshot_20240728_230537_com.huawei.browser.jpg](https://github.com/user-attachments/assets/84bad030-fddc-4cf4-8bb6-50d2a40dcba1)

**Comment by idranme** [comment]
请提供 onebot 协议端日志

**Comment by HMSXEF** [comment]
不太清楚在哪能看到onebot瑟日志，我是用llonebot对接的，上面的logs没有看到任何日志![Screenshot_20240729_095354_com.microsoft.rdc.androidx.jpg](https://github.com/user-attachments/assets/c393c38d-6352-42f3-afdc-b809e6c93da9)

（不好意思）

**Comment by HX-Wrdzgzs** [comment]
不太清楚在哪能看到onebot日志，我是用llonebot对接的，上面的logs没有看到任何日志
（不好意思）[Screenshot_20240729_095354_com.microsoft.rdc.androidx.jpg](https://github.com/user-attachments/assets/4d0a7560-1e11-49b2-919d-da69470d15e9)

**Comment by idranme** [comment]
![1000023794.jpg](https://github.com/user-attachments/assets/2cd69e1b-fe56-4fc6-ab14-8e6c94bffdef)

**Comment by HX-Wrdzgzs** [comment]
![Screenshot_20240730_110015_com.microsoft.rdc.androidx.jpg](https://github.com/user-attachments/assets/0c2bfb7b-fb6e-44e7-843e-4db40d05152c)

**Comment by idranme** [comment]
「写入日志」

**Comment by HX-Wrdzgzs** [comment]
我是需要将music插件重新响应下吗？

**Comment by HX-Wrdzgzs** [comment]
https://share.weiyun.com/lNpv07Up
这是重新响应插件的日志

**Comment by idranme** [comment]
> https://share.weiyun.com/lNpv07Up
> 这是重新响应插件的日志

我这里不方便下载。请找出报错部分并截图。

**Comment by HX-Wrdzgzs** [comment]
**2024/7/30 13:13:27 Takanashi Hoshino BOT(568210745): 语音文件C:\Users\zhou.VMsg\LiteLoaderQQNT-main\data\LLOneBot\temp\38ee89c0-865e-421d-8d1f-8043e0527cafM800000LtUoX2iqLtz.mp3.mp3需要转换成silk 

2024/7/30 13:13:27 Takanashi Hoshino BOT(568210745): FFmpeg处理转换出错:  spawn E:\ffmpeg-2024-06-16-git-fcf72966a5-essentials_build\bin\ffmpeg.exe ENOENT 
**https://share.weiyun.com/lNpv07Up

**Comment by idranme** [comment]
重新安装 FFmpeg

**Comment by HX-Wrdzgzs** [comment]
感谢，已解决
